@baseAddress = http://localhost:5023
@courseId=3fa85f64-5717-4562-b3fc-2c963f66afa6
POST {{baseAddress}}/api/v1/baskets/item
Accept: application/json
Content-Type: application/json
{
  "courseId":"{{courseId}}",
  "courseName": "yyyy",
  "coursePrice": 10
}
###
DELETE {{baseAddress}}/api/v1/baskets/item/{{courseId}}
Accept: application/json
Content-Type: application/json
###
