@baseAddress = http://localhost:5280

GET {{baseAddress}}/api/categories
Accept: application/json
###
Post {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1"
}
###
