@baseAddress = http://localhost:5280
@categoryId=08dcf8d1-01e3-0da4-04bf-1b629e590000
GET {{baseAddress}}/api/categories
Accept: application/json
###
Post {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1"
}
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json
###
