@baseAddress = http://localhost:5280
@categoryId=08dcff11-d1d4-d187-04bf-1b629e590000
@courseId=08dcf8df-9fc1-d3fc-04bf-1b629e590000
@userId=9e590000-1b62-04bf-09c6-08dcff11d209
GET {{baseAddress}}/api/v1/categories
Accept: application/json
###
Post {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1"
}
###
GET {{baseAddress}}/api/v1.2/categories/{{categoryId}}
Accept: application/json
###
POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json

{
  "name": "New Course 3",
  "description": "This is a new course",
  "price": 99.99,
  "imageUrl": "http://example.com/picture.jpg",
  "categoryId": "{{categoryId}}"
}
###
PUT {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json

{
  "Id": "{{courseId}}",
  "name": "New Course 33",
  "description": "This is a new course 33",
  "price": 199.99,
  "imageUrl": "http://example.com/picture2.jpg",
  "categoryId": "{{categoryId}}"
}
###
###
GET {{baseAddress}}/api/courses
Accept: application/json
###
GET {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###
Delete {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###
Get {{baseAddress}}/api/courses/user/{{userId}}
Accept: application/json
###

